### ISSUE TITLE
sasl_secret_t looks wrong

### ISSUE THREAD

**Issue by pbor** [MaterializeInc/rust-sasl#36]
It is defined as

```
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sasl_secret {
    pub len: c_ulong,
    pub data: [c_uchar; 1],
}
```

I am new to this low level rust, so I may be missing something here, but that seems wrong to me: `data` should be a pointer to an allocated string, not an array of length 1. If this gets copied or cloned, you would end up with a password truncated to 1 char, no?

**Comment by pbor** [comment]
To be more clear, I understand that the goal of the C struct is to have a contiguous allocation with the size prepended to the string. So I am okayish with how the struct is defined (since the real string size is not known in advance). The part that looks wrong is the fact that we are deriving `Copy` and `Clone`, which would not be aware of the real size.

**Comment by benesch** [comment]
Thanks! I sent #37 to fix.
