### ISSUE TITLE
How to create sasl_server_plug_t as static?

### ISSUE THREAD

**Issue by Geobert** [MaterializeInc/rust-sasl#50]
Hi,

when I look at existing C plugins, they create a static instance of `sasl_server_plug_t`. 

when I do that I get multiple `*const i8` cannot be shared between threads safely` kind of error.

How do you manage this?

**Comment by benesch** [comment]
Hi @Geobert, you'll need to ask your local C/Rust FFI expert, I'm afraid! This issue tracker is just for reporting bugs or making feature requests, not general questions about usage.
